import OpenAI from "openai";
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(request) {
  try {
    const { prompt } = await request.json();
    if (!prompt) {
      throw Error("No prompt provided");
    }
    const promptResponse = await openai.chat.completions.create({
      messages: [
        {
          role: "system",
          content: 'Your role is that of a educator for 11-12 year old students. You will be asked to perform a task by the user. Your response should be friendly and warm but formal. The response should be at a Grade 6 reading age. Your response should be formatted as a paragraph without line characters or bullet points. The students struggle with long words, and complicated language constructs. Replacing things like "represents," "embodies," "exists as," etc. with a "to be" verb. The students do not understand terms of art around AI training data and bias. If you choose to explain those terms of art, break it down into simpler concepts. Refer to kids as "young people".'
        },
        {
          role: "user",
          content: `${prompt}`,
        },
      ],
      model: "gpt-4o",
    });

    const promptResponseContent = promptResponse.choices[0].message.content;

    const responseRisks = await openai.chat.completions.create({
      messages: [
        {
          role: 'system',
          content: 'Your role is that of a educator for 11-12 year old students. You are educating students about the potential safeguarding risks of using and trusting the products of generative AI. You will receive structured JSON data of the format: { prompt: (a task) , output: (output from generative ai) }. Give me 3-5 potential safeguarding and trust risks for the output generated by AI to fulfill the prompt request. Your response should be formatted with these constraints. Don\'t use numerical list format or dash format, just start the point. Make sure to always Include the new line character at the end of every point apart from the last in order to distinguish between my points so i can extract each point into a list element in html and don\'t give me any other copy apart from those points. Please ensure there are no added spaces when not needed. Your response content should be friendly and warm but formal. The response content should be at a Grade 6 reading age. The students struggle with long words, and complicated language constructs. Replacing things like "represents," "embodies," "exists as," etc. with a "to be" verb. The students do not understand terms of art around AI training data and bias. If you choose to explain those terms of art, break it down into simpler concepts. Refer to kids as "young people".',
        },
        {
          role: "user",
          content: `{ prompt: ${prompt}, output: ${promptResponseContent} }`,
        },
      ],
      model: "gpt-4o",
    });

    const responseRisksContent = responseRisks.choices[0].message.content;

    const splitRiskPoints = responseRisksContent.split("\n");

    return Response.json({ promptResponseContent, splitRiskPoints, modelType: 'summary' });
  } catch (e) {
    throw Error (e.message);
  }
}
